"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, Search, X } from "lucide-react";
import { createContractor, deactivateContractor, getContractorCategories, getContractors, updateContractor } from "@/lib/api/tendering";
import type { Contractor, ContractorCategory, ContractorPayload } from "@/types/tendering";

export default function ContractorsPage() {
  const [contractors, setContractors] = useState<Contractor[]>([]); const [categories, setCategories] = useState<ContractorCategory[]>([]);
  const [categoryId, setCategoryId] = useState(""); const [active, setActive] = useState("true"); const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Contractor | "new" | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { try { setContractors(await getContractors(categoryId || undefined, active === "all" ? undefined : active === "true")); setError(null); } catch (err) { setError(err instanceof Error ? err.message : "Could not load contractors"); } finally { setLoading(false); } }
  useEffect(() => { getContractorCategories().then(setCategories).catch((err) => setError(err instanceof Error ? err.message : "Could not load categories")); }, []);
  useEffect(() => { let current = true; getContractors(categoryId || undefined, active === "all" ? undefined : active === "true").then((items) => { if (current) { setContractors(items); setError(null); } }).catch((err) => { if (current) setError(err instanceof Error ? err.message : "Could not load contractors"); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [categoryId, active]);
  const filtered = useMemo(() => contractors.filter((item) => [item.name, item.contact_name, item.email].join(" ").toLowerCase().includes(search.toLowerCase())), [contractors, search]);
  async function save(payload: ContractorPayload) { if (editing === "new") await createContractor(payload); else if (editing) await updateContractor(editing.id, payload); setEditing(null); await load(); }
  async function toggle(item: Contractor) { if (item.active) await deactivateContractor(item.id); else await updateContractor(item.id, { active: true }); await load(); }
  return <main className="min-h-screen bg-[var(--ch-page-bg)] px-6 py-8 text-[var(--ch-text-primary)] lg:px-10"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex items-end justify-between border-b border-[var(--ch-border)] pb-6"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--ch-text-muted)]">Tendering</p><h1 className="mt-1 text-3xl font-semibold">Contractors</h1><p className="mt-2 text-sm text-[var(--ch-text-muted)]">Reusable contractor contacts and trade categories.</p></div><button onClick={() => setEditing("new")} className="inline-flex items-center gap-2 rounded-lg bg-[var(--ch-accent)] px-4 py-2.5 text-sm font-semibold text-[var(--ch-accent-text)]"><Plus size={16}/>New contractor</button></header>
    <section className="grid gap-3 rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)] p-4 md:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--ch-text-muted)]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search contractors" className="w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] py-2.5 pl-9 pr-3 text-sm"/></label><select value={categoryId} onChange={(e) => setCategoryId(e.target.value)} className="rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] px-3 py-2.5 text-sm"><option value="">All categories</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={active} onChange={(e) => setActive(e.target.value)} className="rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] px-3 py-2.5 text-sm"><option value="true">Active</option><option value="false">Inactive</option><option value="all">All</option></select></section>
    {error ? <p className="rounded-lg bg-[var(--ch-error-bg)] p-3 text-sm text-[var(--ch-error-text)]">{error}</p> : null}
    <section className="overflow-hidden rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)]">{loading ? <p className="p-8 text-sm text-[var(--ch-text-muted)]">Loading contractors…</p> : filtered.length === 0 ? <p className="p-8 text-center text-sm text-[var(--ch-text-muted)]">No contractors match these filters.</p> : <table className="w-full text-left text-sm"><thead className="bg-[var(--ch-surface-muted)] text-xs uppercase text-[var(--ch-text-muted)]"><tr><th className="px-4 py-3">Contractor</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Trades</th><th className="px-4 py-3">Status</th><th/></tr></thead><tbody className="divide-y divide-[var(--ch-border)]">{filtered.map((item) => <tr key={item.id}><td className="px-4 py-3 font-semibold">{item.name}</td><td className="px-4 py-3 text-[var(--ch-text-secondary)]">{item.contact_name || "—"}<div className="text-xs text-[var(--ch-text-muted)]">{item.email || item.phone || "No contact details"}</div></td><td className="px-4 py-3">{item.categories.map((category) => category.name).join(", ") || "Other"}</td><td className="px-4 py-3">{item.active ? "Active" : "Inactive"}</td><td className="px-4 py-3 text-right"><button onClick={() => setEditing(item)} className="mr-3 text-[var(--ch-accent)]">Edit</button><button onClick={() => void toggle(item)} className="text-[var(--ch-text-muted)]">{item.active ? "Deactivate" : "Reactivate"}</button></td></tr>)}</tbody></table>}</section>
    {editing ? <ContractorModal contractor={editing === "new" ? null : editing} categories={categories} onClose={() => setEditing(null)} onSave={save}/> : null}
  </div></main>;
}

function ContractorModal({ contractor, categories, onClose, onSave }: { contractor: Contractor | null; categories: ContractorCategory[]; onClose: () => void; onSave: (payload: ContractorPayload) => Promise<void> }) {
  const [values, setValues] = useState<ContractorPayload>({ name: contractor?.name || "", contact_name: contractor?.contact_name || "", email: contractor?.email || "", phone: contractor?.phone || "", address: contractor?.address || "", notes: contractor?.notes || "", active: contractor?.active ?? true, category_ids: contractor?.categories.map((item) => item.id) || [] }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { await onSave(values); } catch (err) { setError(err instanceof Error ? err.message : "Could not save contractor"); setSaving(false); } }
  function field(key: keyof ContractorPayload, value: string) { setValues((current) => ({ ...current, [key]: value })); }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={onClose}><form onSubmit={submit} onClick={(e) => e.stopPropagation()} className="max-h-[90vh] w-full max-w-xl space-y-4 overflow-y-auto rounded-xl bg-[var(--ch-page-bg)] p-5 shadow-2xl"><div className="flex justify-between"><h2 className="text-lg font-semibold">{contractor ? "Edit contractor" : "New contractor"}</h2><button type="button" onClick={onClose}><X size={18}/></button></div><div className="grid gap-3 sm:grid-cols-2">{(["name","contact_name","email","phone","address"] as const).map((key) => <label key={key} className={`text-xs text-[var(--ch-text-muted)] ${key === "address" ? "sm:col-span-2" : ""}`}>{key.replace("_", " ")}<input required={key === "name"} value={String(values[key] || "")} onChange={(e) => field(key, e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm"/></label>)}</div><fieldset><legend className="mb-2 text-xs text-[var(--ch-text-muted)]">Trade categories</legend><div className="grid grid-cols-2 gap-2">{categories.map((item) => <label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={values.category_ids.includes(item.id)} onChange={(e) => setValues((current) => ({ ...current, category_ids: e.target.checked ? [...current.category_ids, item.id] : current.category_ids.filter((id) => id !== item.id) }))}/>{item.name}</label>)}</div></fieldset><label className="block text-xs text-[var(--ch-text-muted)]">Notes<textarea value={values.notes || ""} onChange={(e) => field("notes", e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm"/></label>{error ? <p className="text-sm text-[var(--ch-error-text)]">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-[var(--ch-border)] px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-[var(--ch-accent)] px-4 py-2 text-sm font-semibold text-[var(--ch-accent-text)]">{saving ? "Saving…" : "Save contractor"}</button></div></form></div>;
}
