import { useCallback, useEffect, useMemo, useState } from "react";
import { FileText, Plus, Trash2, Upload } from "lucide-react";
import { getBudget, getBudgets, type Budget, type BudgetLine } from "@/lib/api/costbook";
import { awardTenderPackage, cancelTenderBid, createTenderBid, createTenderPackage, deleteTenderDocument, getContractorCategories, getContractors, getTenderPackages, tenderBidDocumentUrl, tenderDocumentUrl, updateTenderBid, updateTenderPackage, uploadTenderBidDocument, uploadTenderDocument } from "@/lib/api/tendering";
import type { Contractor, ContractorCategory, TenderBid, TenderDocumentType, TenderLineItem, TenderPackage, TenderStatus } from "@/types/tendering";

const statuses: TenderStatus[] = ["draft", "sent", "bids_in", "compared", "awarded", "cancelled"];
const money = (value?: string | null) => value ? new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(Number(value)) : "—";
const field = "rounded-md border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm";

export function TenderPackagesPanel({ propertyId }: { propertyId: string }) {
  const [packages, setPackages] = useState<TenderPackage[]>([]);
  const [categories, setCategories] = useState<ContractorCategory[]>([]);
  const [creating, setCreating] = useState(false);
  const [categoryId, setCategoryId] = useState(""); const [scope, setScope] = useState(""); const [dueDate, setDueDate] = useState("");
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const showError = useCallback((err: unknown) => { setError(err instanceof Error ? err.message : "Tendering request failed"); }, []);
  async function load() { setPackages(await getTenderPackages(propertyId)); }
  useEffect(() => { let active = true; Promise.all([getTenderPackages(propertyId), getContractorCategories()]).then(([p, c]) => { if (active) { setPackages(p); setCategories(c); } }).catch(showError).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [propertyId, showError]);
  async function create(e: React.FormEvent) { e.preventDefault(); try { await createTenderPackage(propertyId, { category_id: categoryId, scope_description: scope, due_date: dueDate || null }); setCreating(false); setCategoryId(""); setScope(""); setDueDate(""); await load(); } catch (err) { showError(err); } }
  return <section className="mb-4 rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)] p-4">
    <div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">Tender Packages</h3><p className="mt-1 text-xs text-[var(--ch-text-muted)]">Invite up to three contractors, compare quotes, and award to a Costbook line.</p></div><button onClick={() => setCreating(!creating)} className="inline-flex items-center gap-1 rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)]"><Plus size={14}/>New package</button></div>
    {error && <p className="mt-3 rounded-md bg-[var(--ch-error-bg)] p-2 text-sm text-[var(--ch-error-text)]">{error}</p>}
    {creating && <form onSubmit={create} className="mt-4 grid gap-3 rounded-lg bg-[var(--ch-surface-muted)] p-3 sm:grid-cols-2"><select required value={categoryId} onChange={e => setCategoryId(e.target.value)} className={field}><option value="">Select trade</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} className={field}/><textarea required value={scope} onChange={e => setScope(e.target.value)} placeholder="Scope description" className={`${field} min-h-20 sm:col-span-2`}/><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setCreating(false)} className="rounded-md border border-[var(--ch-border)] px-3 py-2 text-xs">Cancel</button><button className="rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)]">Create</button></div></form>}
    <div className="mt-4 space-y-4">{loading ? <p className="text-sm text-[var(--ch-text-muted)]">Loading…</p> : packages.length === 0 ? <p className="rounded-lg bg-[var(--ch-surface-muted)] p-4 text-center text-sm text-[var(--ch-text-muted)]">No tender packages yet.</p> : packages.map(item => <PackageCard key={item.id} item={item} reload={load} showError={showError}/>)}</div>
  </section>;
}

function PackageCard({ item, reload, showError }: { item: TenderPackage; reload: () => Promise<void>; showError: (e: unknown) => void }) {
  const activeBids = item.bids.filter(b => b.status !== "cancelled");
  const [contractors, setContractors] = useState<Contractor[]>([]); const [contractorId, setContractorId] = useState("");
  const [compare, setCompare] = useState(false); const [awarding, setAwarding] = useState(false);
  useEffect(() => { getContractors(item.category_id, true).then(setContractors).catch(showError); }, [item.category_id, showError]);
  async function run(action: () => Promise<unknown>) { try { await action(); await reload(); } catch (e) { showError(e); } }
  return <article className="rounded-lg border border-[var(--ch-border)] p-3">
    <div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.category.name}</p><p className="mt-1 text-sm text-[var(--ch-text-secondary)]">{item.scope_description}</p><p className="mt-1 text-xs text-[var(--ch-text-muted)]">Due {item.due_date || "not set"} · {activeBids.filter(b => b.status === "received" || b.status === "reviewed").length} of 3 bids received</p></div><select value={item.status} disabled={item.status === "awarded"} onChange={e => void run(() => updateTenderPackage(item.id, { status: e.target.value as TenderStatus }))} className="rounded-full border border-[var(--ch-border)] bg-[var(--ch-surface-muted)] px-2 py-1 text-xs font-semibold">{statuses.map(s => <option key={s}>{s}</option>)}</select></div>
    <PackageDocuments item={item} reload={reload} showError={showError}/>
    {item.award ? <p className="mt-3 rounded-md bg-[var(--ch-success-bg)] p-3 text-sm">Awarded · <a className="font-semibold text-[var(--ch-accent)]" href={`/costbook/budgets/${item.award.purchase_order?.budget_id || ""}`}>PO {item.award.purchase_order?.po_number || item.award.po_id}</a></p> : <><div className="mt-4 flex flex-wrap items-center gap-2"><select value={contractorId} onChange={e => setContractorId(e.target.value)} className={field}><option value="">Invite contractor…</option>{contractors.filter(c => !activeBids.some(b => b.contractor_id === c.id)).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={!contractorId || activeBids.length >= 3} onClick={() => void run(async () => { await createTenderBid(item.id, contractorId); setContractorId(""); })} className="rounded-md border border-[var(--ch-border)] px-3 py-2 text-xs disabled:opacity-50">Invite</button><button onClick={() => setCompare(!compare)} className="rounded-md border border-[var(--ch-border)] px-3 py-2 text-xs">{compare ? "Hide" : "Compare"}</button><button disabled={!activeBids.some(b => b.status === "reviewed")} onClick={() => setAwarding(!awarding)} className="rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)] disabled:opacity-50">Award</button></div>
    <div className="mt-3 grid gap-3 xl:grid-cols-3">{activeBids.map(bid => <BidCard key={bid.id} bid={bid} reload={reload} showError={showError}/>)}</div>
    {compare && <Comparison bids={activeBids}/>} {awarding && <AwardForm item={item} bids={activeBids} reload={reload} showError={showError}/>}</>}
  </article>;
}

function PackageDocuments({ item, reload, showError }: { item: TenderPackage; reload: () => Promise<void>; showError: (e: unknown) => void }) {
  async function upload(type: TenderDocumentType, file?: File) { if (!file) return; try { await uploadTenderDocument(item.id, type, file); await reload(); } catch (e) { showError(e); } }
  return <div className="mt-3"><div className="space-y-1">{item.documents.map(d => <div key={d.id} className="flex items-center gap-2 rounded-md bg-[var(--ch-surface-muted)] px-3 py-2 text-xs"><FileText size={14}/><a target="_blank" href={tenderDocumentUrl(d.id)} className="min-w-0 flex-1 truncate text-[var(--ch-accent)]">{d.original_filename}</a><span>{d.document_type}</span><button onClick={() => void deleteTenderDocument(d.id).then(reload).catch(showError)}><Trash2 size={14}/></button></div>)}</div><div className="mt-2 flex gap-2">{(["plan", "markup", "spec"] as TenderDocumentType[]).map(type => <label key={type} className="cursor-pointer rounded-md border border-[var(--ch-border)] px-2 py-1.5 text-xs"><Upload className="mr-1 inline" size={13}/>Add {type}<input type="file" accept="application/pdf" className="hidden" onChange={e => void upload(type, e.target.files?.[0])}/></label>)}</div></div>;
}

function BidCard({ bid, reload, showError }: { bid: TenderBid; reload: () => Promise<void>; showError: (e: unknown) => void }) {
  const [amount, setAmount] = useState(bid.quote_amount || bid.extracted_amount || ""); const [items, setItems] = useState<TenderLineItem[]>(bid.extracted_line_items || []); const [exclusions, setExclusions] = useState(bid.excluded_scope_notes || ""); const [notes, setNotes] = useState(bid.reviewer_notes || "");
  async function save() { try { await updateTenderBid(bid.id, { quote_amount: amount, extracted_line_items: items, excluded_scope_notes: exclusions || null, reviewer_notes: notes || null }); await reload(); } catch (e) { showError(e); } }
  return <div className="rounded-lg bg-[var(--ch-surface-muted)] p-3 text-sm"><div className="flex justify-between"><div><strong>{bid.contractor.name}</strong><p className="text-xs text-[var(--ch-text-muted)]">{bid.status}</p></div><button title="Cancel bid" onClick={() => void cancelTenderBid(bid.id).then(reload).catch(showError)}><Trash2 size={14}/></button></div>
    {bid.documents.map(d => <a key={d.id} target="_blank" href={tenderBidDocumentUrl(d.id)} className="mt-2 block truncate text-xs text-[var(--ch-accent)]">{d.original_filename}</a>)}
    <label className="mt-2 block cursor-pointer rounded-md border border-[var(--ch-border)] px-2 py-1.5 text-center text-xs"><Upload className="mr-1 inline" size={13}/>{bid.documents.length ? "Replace/add quote" : "Upload quote PDF"}<input type="file" accept="application/pdf" className="hidden" onChange={e => { const f = e.target.files?.[0]; if (f) void uploadTenderBidDocument(bid.id, f).then(reload).catch(showError); }}/></label>
    {(bid.status === "received" || bid.status === "reviewed") && <div className="mt-3 space-y-2"><label className="block text-xs">Confirmed amount<input value={amount} onChange={e => setAmount(e.target.value)} inputMode="decimal" className={`${field} mt-1 w-full`}/></label>{items.map((line, i) => <div key={i} className="grid grid-cols-[1fr_7rem] gap-1"><input value={line.description} onChange={e => setItems(items.map((x, n) => n === i ? {...x, description: e.target.value} : x))} className={field}/><input value={line.amount} onChange={e => setItems(items.map((x, n) => n === i ? {...x, amount: e.target.value} : x))} className={field}/></div>)}<button onClick={() => setItems([...items, { description: "", amount: "0.00" }])} className="text-xs text-[var(--ch-accent)]">+ Line item</button><textarea value={exclusions} onChange={e => setExclusions(e.target.value)} placeholder="Exclusions" className={`${field} block w-full`}/><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Reviewer notes" className={`${field} block w-full`}/><button onClick={() => void save()} className="w-full rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)]">Confirm bid</button></div>}
  </div>;
}

function Comparison({ bids }: { bids: TenderBid[] }) { return <div className="mt-4 overflow-x-auto"><div className="grid min-w-[720px] gap-3" style={{ gridTemplateColumns: `repeat(${Math.max(bids.length, 1)}, minmax(220px, 1fr))` }}>{bids.map(b => <div key={b.id} className="rounded-lg border border-[var(--ch-border)] p-3"><strong>{b.contractor.name}</strong><p className="my-2 text-lg font-semibold">{money(b.quote_amount)}</p>{b.extracted_line_items?.map((x, i) => <div key={i} className="flex justify-between gap-3 text-xs"><span>{x.description}</span><span>{money(x.amount)}</span></div>)}<p className="mt-3 whitespace-pre-wrap text-xs"><b>Exclusions:</b> {b.excluded_scope_notes || "None noted"}</p><p className="mt-2 whitespace-pre-wrap text-xs"><b>Review notes:</b> {b.reviewer_notes || "None"}</p></div>)}</div></div>; }

function AwardForm({ item, bids, reload, showError }: { item: TenderPackage; bids: TenderBid[]; reload: () => Promise<void>; showError: (e: unknown) => void }) {
  const reviewed = bids.filter(b => b.status === "reviewed"); const [winning, setWinning] = useState(reviewed[0]?.id || ""); const [budgets, setBudgets] = useState<Budget[]>([]); const [budgetId, setBudgetId] = useState(""); const [budget, setBudget] = useState<Budget | null>(null); const [lineId, setLineId] = useState(""); const [instructions, setInstructions] = useState(""); const [projectDate, setProjectDate] = useState(""); const [contractorDate, setContractorDate] = useState("");
  useEffect(() => { getBudgets().then(setBudgets).catch(showError); }, [showError]);
  async function chooseBudget(id: string) { setBudgetId(id); setLineId(""); setBudget(id ? await getBudget(id).catch(error => { showError(error); return null; }) : null); }
  const lines = useMemo(() => sortMatchingLines(budget?.lines || [], item.category.name), [budget, item.category.name]);
  async function submit(e: React.FormEvent) { e.preventDefault(); try { await awardTenderPackage(item.id, { winning_bid_id: winning, budget_id: budgetId, budget_line_id: lineId, award_instructions: instructions, project_start_date: projectDate, contractor_start_date: contractorDate }); await reload(); } catch (err) { showError(err); } }
  return <form onSubmit={submit} className="mt-4 grid gap-3 rounded-lg border border-[var(--ch-border)] p-3 sm:grid-cols-2"><h4 className="font-semibold sm:col-span-2">Award and generate purchase order</h4><select required value={winning} onChange={e => setWinning(e.target.value)} className={field}>{reviewed.map(b => <option key={b.id} value={b.id}>{b.contractor.name} — {money(b.quote_amount)}</option>)}</select><select required value={budgetId} onChange={e => void chooseBudget(e.target.value)} className={field}><option value="">Select Costbook budget explicitly</option>{budgets.map(b => <option key={b.id} value={b.id}>{b.label}</option>)}</select><select required value={lineId} onChange={e => setLineId(e.target.value)} className={`${field} sm:col-span-2`}><option value="">Select budget line explicitly</option>{lines.map(({ line, match }) => <option key={line.id} value={line.id}>{match ? "Suggested · " : ""}{line.po_number} — {line.description}</option>)}</select><textarea required value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="Award instructions" className={`${field} sm:col-span-2`}/><label className="text-xs">Project start<input required type="date" value={projectDate} onChange={e => setProjectDate(e.target.value)} className={`${field} mt-1 block w-full`}/></label><label className="text-xs">Contractor start<input required type="date" value={contractorDate} onChange={e => setContractorDate(e.target.value)} className={`${field} mt-1 block w-full`}/></label><button className="rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)] sm:col-span-2">Award and create PO</button></form>;
}

function sortMatchingLines(lines: BudgetLine[], category: string): { line: BudgetLine; match: boolean }[] { const words = category.toLowerCase().split(/\W+/).filter(w => w.length > 2); return lines.map(line => ({ line, match: words.some(w => `${line.section} ${line.description}`.toLowerCase().includes(w)) })).sort((a, b) => Number(b.match) - Number(a.match) || a.line.po_number.localeCompare(b.line.po_number)); }
