import { useEffect, useState } from "react";
import { FileText, Plus, Trash2, Upload } from "lucide-react";
import { createTenderPackage, deleteTenderDocument, getContractorCategories, getTenderPackages, tenderDocumentUrl, updateTenderPackage, uploadTenderDocument } from "@/lib/api/tendering";
import type { FinancingProperty } from "@/types/financing";
import type { ContractorCategory, TenderDocumentType, TenderPackage, TenderStatus } from "@/types/tendering";

const statuses: TenderStatus[] = ["draft", "sent", "bids_in", "compared", "awarded", "cancelled"];

export function TenderPackagesPanel({ property }: { property: FinancingProperty }) {
  const [packages, setPackages] = useState<TenderPackage[]>([]); const [categories, setCategories] = useState<ContractorCategory[]>([]);
  const [creating, setCreating] = useState(false); const [categoryId, setCategoryId] = useState(""); const [scope, setScope] = useState(""); const [dueDate, setDueDate] = useState("");
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  async function load() { setPackages(await getTenderPackages(property.property_id)); }
  useEffect(() => { let active = true; Promise.all([getTenderPackages(property.property_id), getContractorCategories()]).then(([nextPackages, nextCategories]) => { if (active) { setPackages(nextPackages); setCategories(nextCategories); } }).catch((err) => { if (active) setError(err instanceof Error ? err.message : "Could not load tender packages"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [property.property_id]);
  async function create(e: React.FormEvent) { e.preventDefault(); try { await createTenderPackage(property.property_id, { category_id: categoryId, scope_description: scope, due_date: dueDate || null }); setCreating(false); setCategoryId(""); setScope(""); setDueDate(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Could not create tender package"); } }
  async function status(id: string, next: TenderStatus) { await updateTenderPackage(id, { status: next }); await load(); }
  async function upload(id: string, type: TenderDocumentType, file?: File) { if (!file) return; try { await uploadTenderDocument(id, type, file); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Could not upload document"); } }
  async function remove(id: string) { await deleteTenderDocument(id); await load(); }
  return <section className="mb-4 rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)] p-4"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">Tender Packages</h3><p className="mt-1 text-xs text-[var(--ch-text-muted)]">Trade scopes and plans for contractor tendering.</p></div><button onClick={() => setCreating((value) => !value)} className="inline-flex items-center gap-1 rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)]"><Plus size={14}/>New Tender Package</button></div>
    {error ? <p className="mt-3 rounded-md bg-[var(--ch-error-bg)] p-2 text-sm text-[var(--ch-error-text)]">{error}</p> : null}
    {creating ? <form onSubmit={create} className="mt-4 grid gap-3 rounded-lg bg-[var(--ch-surface-muted)] p-3 sm:grid-cols-2"><select required value={categoryId} onChange={(e) => setCategoryId(e.target.value)} className="rounded-md border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm"><option value="">Select trade</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} className="rounded-md border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm"/><textarea required value={scope} onChange={(e) => setScope(e.target.value)} placeholder="Scope description" className="min-h-20 rounded-md border border-[var(--ch-border)] bg-[var(--ch-surface)] px-3 py-2 text-sm sm:col-span-2"/><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setCreating(false)} className="rounded-md border border-[var(--ch-border)] px-3 py-2 text-xs">Cancel</button><button className="rounded-md bg-[var(--ch-accent)] px-3 py-2 text-xs font-semibold text-[var(--ch-accent-text)]">Create package</button></div></form> : null}
    <div className="mt-4 space-y-3">{loading ? <p className="text-sm text-[var(--ch-text-muted)]">Loading tender packages…</p> : packages.length === 0 ? <p className="rounded-lg bg-[var(--ch-surface-muted)] p-4 text-center text-sm text-[var(--ch-text-muted)]">No tender packages for this property yet.</p> : packages.map((item) => <article key={item.id} className="rounded-lg border border-[var(--ch-border)] p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.category.name}</p><p className="mt-1 text-sm text-[var(--ch-text-secondary)]">{item.scope_description}</p><p className="mt-1 text-xs text-[var(--ch-text-muted)]">Due {item.due_date || "not set"}</p></div><select value={item.status} onChange={(e) => void status(item.id, e.target.value as TenderStatus)} className="rounded-full border border-[var(--ch-border)] bg-[var(--ch-surface-muted)] px-2 py-1 text-xs font-semibold">{statuses.map((value) => <option key={value}>{value}</option>)}</select></div><div className="mt-3 space-y-2">{item.documents.map((document) => <div key={document.id} className="flex items-center gap-2 rounded-md bg-[var(--ch-surface-muted)] px-3 py-2 text-xs"><FileText size={14}/><a target="_blank" rel="noreferrer" href={tenderDocumentUrl(document.id)} className="min-w-0 flex-1 truncate text-[var(--ch-accent)]">{document.original_filename}</a><span className="uppercase text-[var(--ch-text-muted)]">{document.document_type}</span><button onClick={() => void remove(document.id)} aria-label="Delete document"><Trash2 size={14}/></button></div>)}<div className="flex flex-wrap gap-2">{(["plan","markup","spec"] as TenderDocumentType[]).map((type) => <label key={type} className="inline-flex cursor-pointer items-center gap-1 rounded-md border border-[var(--ch-border)] px-2 py-1.5 text-xs"><Upload size={13}/>Add {type}<input type="file" accept="application/pdf" className="hidden" onChange={(e) => void upload(item.id, type, e.target.files?.[0])}/></label>)}</div></div></article>)}</div>
  </section>;
}
