"use client";

import { useEffect, useMemo, useState } from "react";
import { approveAllClean, approveImportRow, getBatch, listBatches, listRentalUnits, patchImportRow, rejectImportRow, templateUrl, uploadLeaseImport, type ImportBatch, type ImportRow, type RentalUnit } from "@/lib/api/rentals";

function flags(row:ImportRow):string[] { const value=row.confidence?.flags; return Array.isArray(value) ? value.map(String) : []; }
function confidence(row:ImportRow):number { const values=Object.entries(row.confidence||{}).filter(([k,v])=>k!=="flags"&&typeof v==="number").map(([,v])=>v as number); return values.length?Math.min(...values):0; }

export default function LeaseImportPage() {
  const [batches,setBatches]=useState<ImportBatch[]>([]); const [batch,setBatch]=useState<ImportBatch|null>(null); const [units,setUnits]=useState<RentalUnit[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=()=>Promise.all([listBatches(),listRentalUnits()]).then(([b,u])=>{setBatches(b);setUnits(u)}).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  async function refresh(){ if(batch)setBatch(await getBatch(batch.id)); await load(); }
  async function upload(file:File){setBusy(true);try{const result=await uploadLeaseImport(file);setBatch(result);await load()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}
  const rows=useMemo(()=>[...(batch?.rows||[])].sort((a,b)=>Number(b.match_type==="unresolved")-Number(a.match_type==="unresolved")||flags(b).length-flags(a).length||confidence(a)-confidence(b)),[batch]);
  return <main className="mx-auto max-w-7xl p-6 lg:p-10">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--ch-border)] pb-6"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--ch-text-muted)]">Rentals · PRIVI</p><h1 className="mt-1 text-3xl font-semibold">Lease Import</h1><p className="mt-2 text-sm text-[var(--ch-text-muted)]">Upload, review, and explicitly approve rent-roll changes.</p></div><div className="flex gap-2"><a href={templateUrl} className="rounded-lg border border-[var(--ch-border)] px-4 py-2 text-sm font-semibold">Download Template</a><label className="cursor-pointer rounded-lg bg-[var(--ch-accent)] px-4 py-2 text-sm font-semibold text-[var(--ch-accent-text)]">{busy?"Extracting…":"Upload .xlsx"}<input className="hidden" type="file" accept=".xlsx" disabled={busy} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label></div></header>
    {error&&<div className="mt-4 rounded-lg bg-[var(--ch-error-bg)] p-3 text-sm text-[var(--ch-error-text)]">{error}</div>}
    <section className="mt-6 grid gap-3 md:grid-cols-3">{batches.map(item=><button key={item.id} onClick={()=>getBatch(item.id).then(setBatch).catch(e=>setError(e.message))} className="rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)] p-4 text-left"><strong>{item.source_filename}</strong><div className="mt-2 text-xs text-[var(--ch-text-muted)]">{item.status} · {item.rows_pending}/{item.total_rows} pending</div></button>)}</section>
    {batch&&<section className="mt-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Batch #{batch.id}</h2><p className="text-sm text-[var(--ch-text-muted)]">{batch.source_filename}</p></div><button onClick={async()=>{setBusy(true);try{const r=await approveAllClean(batch.id);alert(`${r.approved} approved; ${r.skipped_for_review} left for review`);await refresh()}catch(e){setError(e instanceof Error?e.message:"Approval failed")}finally{setBusy(false)}}} className="rounded-lg bg-[var(--ch-accent)] px-4 py-2 text-sm font-semibold text-[var(--ch-accent-text)]">Approve all clean rows</button></div>
      <div className="mt-4 space-y-3">{rows.map(row=><ReviewRow key={row.id} row={row} units={units} onDone={refresh}/>)}</div>
    </section>}
  </main>
}

function ReviewRow({row,units,onDone}:{row:ImportRow;units:RentalUnit[];onDone:()=>Promise<void>}) {
  const [open,setOpen]=useState(false); const [json,setJson]=useState(JSON.stringify(row.parsed_data,null,2)); const [unitSearch,setUnitSearch]=useState(""); const [unitId,setUnitId]=useState(row.matched_unit_id?String(row.matched_unit_id):""); const [action,setAction]=useState(row.suggested_action||"skip"); const score=confidence(row); const color=score>=.8?"var(--ch-success-text)":score>=.6?"var(--ch-warning-text)":"var(--ch-error-text)";
  const shownUnits=units.filter(u=>`${u.street_address} ${u.unit_label||""}`.toLowerCase().includes(unitSearch.toLowerCase()));
  async function save(){await patchImportRow(row.id,{parsed_data:JSON.parse(json),matched_unit_id:unitId?Number(unitId):null,match_type:unitId?"existing_unit":row.match_type,suggested_action:action});await onDone()}
  return <article className="rounded-xl border border-[var(--ch-border)] bg-[var(--ch-surface)]"><button onClick={()=>setOpen(!open)} className="flex w-full items-center gap-3 p-4 text-left"><span className="font-semibold">Row {row.source_row_number}</span><span className="rounded-full border px-2 py-0.5 text-xs">{row.match_type||"unmatched"}</span><span className="rounded-full border px-2 py-0.5 text-xs">{row.suggested_action||"no action"}</span><span style={{color}} className="text-xs font-bold">{Math.round(score*100)}%</span><span className="ml-auto text-xs text-[var(--ch-text-muted)]">{row.review_status}</span></button>
    {open&&<div className="grid gap-4 border-t border-[var(--ch-border)] p-4 lg:grid-cols-2"><div><h3 className="text-xs font-bold uppercase text-[var(--ch-text-muted)]">Raw source</h3><pre className="mt-2 overflow-auto rounded-lg bg-[var(--ch-page-bg)] p-3 text-xs">{JSON.stringify(row.raw_data,null,2)}</pre>{flags(row).map(flag=><p key={flag} className="mt-2 text-xs text-[var(--ch-error-text)]">⚠ {flag}</p>)}</div><div><h3 className="text-xs font-bold uppercase text-[var(--ch-text-muted)]">Parsed data</h3><textarea value={json} onChange={e=>setJson(e.target.value)} rows={14} className="mt-2 w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] p-3 font-mono text-xs"/><input value={unitSearch} onChange={e=>setUnitSearch(e.target.value)} placeholder="Search units" className="mt-2 w-full rounded-lg border border-[var(--ch-border)] bg-transparent px-3 py-2 text-sm"/><select value={unitId} onChange={e=>setUnitId(e.target.value)} className="mt-2 w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] px-3 py-2 text-sm"><option value="">Unresolved / new unit</option>{shownUnits.map(u=><option key={u.id} value={u.id}>{u.street_address}{u.unit_label?` — ${u.unit_label}`:""}</option>)}</select><select value={action} onChange={e=>setAction(e.target.value)} className="mt-2 w-full rounded-lg border border-[var(--ch-border)] bg-[var(--ch-page-bg)] px-3 py-2 text-sm">{["create_lease","renew_lease","update_lease","skip"].map(a=><option key={a}>{a}</option>)}</select><div className="mt-3 flex justify-end gap-2"><button onClick={()=>rejectImportRow(row.id).then(onDone)} className="rounded-lg border px-3 py-2 text-sm">Reject</button><button onClick={()=>save().catch(e=>alert(e.message))} className="rounded-lg border px-3 py-2 text-sm">Save edits</button><button onClick={()=>save().then(()=>approveImportRow(row.id)).then(onDone).catch(e=>alert(e.message))} className="rounded-lg bg-[var(--ch-accent)] px-3 py-2 text-sm font-semibold text-[var(--ch-accent-text)]">Approve</button></div></div></div>}
  </article>
}
