"use client";
import {useEffect,useState} from "react";
import * as api from "@/lib/api/rental-reports";

export default function ReportsPage(){
  const [candidates,setCandidates]=useState<api.Candidate[]>([]),[reports,setReports]=useState<api.Report[]>([]),[selected,setSelected]=useState<Set<number>>(new Set()),[title,setTitle]=useState("Rental Inspection Report"),[days,setDays]=useState(7),[email,setEmail]=useState(""),[created,setCreated]=useState<api.Report|null>(null),[link,setLink]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([api.candidates(),api.reports()]).then(([c,r])=>{setCandidates(c);setReports(r)}).catch(e=>setError(e.message))},[]);
  async function build(){setBusy(true);setError("");try{const report=await api.create(title,[...selected],days);setCreated(report);setReports(current=>[report,...current])}catch(e){setError(e instanceof Error?e.message:"Could not create report")}finally{setBusy(false)}}
  async function send(){if(!created)return;setBusy(true);setError("");try{const result=await api.send(created.id,email);setCreated(result.report);setLink(result.public_url)}catch(e){setError(e instanceof Error?e.message:"Could not send report")}finally{setBusy(false)}}
  async function removeReport(id:string){if(!window.confirm("Delete this report and its discussion? The underlying inspections and photos will be kept."))return;setError("");try{await api.remove(id);setReports(current=>current.filter(report=>report.id!==id));if(created?.id===id){setCreated(null);setLink("")}}catch(e){setError(e instanceof Error?e.message:"Could not delete report")}}
  function toggleInspection(id:number){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
  return <main className="mx-auto max-w-5xl p-4 sm:p-8"><h1 className="text-3xl font-bold">Inspection Reports</h1><p className="mt-2 text-[var(--ch-text-muted)]">Select each property’s most recent submitted inspection.</p>{error&&<p className="my-4 rounded-xl bg-[var(--ch-error-bg)] p-3 text-[var(--ch-error-text)]">{error}</p>}<section className="mt-6 rounded-2xl border bg-[var(--ch-surface)] p-4"><div className="grid gap-3 sm:grid-cols-3"><input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl border p-3 sm:col-span-2"/><label className="text-sm">Link expires in days<input type="number" min="1" max="30" value={days} onChange={e=>setDays(Number(e.target.value))} className="mt-1 w-full rounded-xl border p-3"/></label></div><div className="mt-5 space-y-2">{candidates.map(c=><label key={c.inspection_id} className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.has(c.inspection_id)} onChange={()=>toggleInspection(c.inspection_id)}/><span><strong>{c.address} {c.unit_label||""}</strong><span className="block text-sm text-[var(--ch-text-muted)]">{c.inspection_date} · Front {c.front_yard_score??"—"} · Back {c.back_yard_score??"—"}</span></span></label>)}</div><button disabled={busy||selected.size===0} onClick={build} className="mt-4 rounded-xl bg-[var(--ch-accent)] px-5 py-3 font-bold text-white disabled:opacity-50">Create report</button></section>{created&&<section className="mt-6 rounded-2xl border bg-[var(--ch-surface)] p-4"><h2 className="text-xl font-bold">Email secure report</h2><p className="mt-1 text-sm text-[var(--ch-text-muted)]">{created.items.length} properties · expires {new Date(created.expires_at).toLocaleString()}</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Recipient email" className="flex-1 rounded-xl border p-3"/><button disabled={busy||!email} onClick={send} className="rounded-xl bg-[var(--ch-accent)] px-5 py-3 font-bold text-white disabled:opacity-50">Send email</button></div>{link&&<p className="mt-3 break-all text-sm">Sent: <a className="text-[var(--ch-accent)] underline" href={link}>{link}</a></p>}</section>}<section className="mt-8"><h2 className="text-xl font-bold">Recent reports</h2>{reports.map(r=><div key={r.id} className="mt-2 flex items-center justify-between gap-3 rounded-xl border bg-[var(--ch-surface)] p-3"><div><strong>{r.title}</strong><div className="text-sm text-[var(--ch-text-muted)]">{r.status} · {r.items.length} properties · expires {new Date(r.expires_at).toLocaleDateString()}</div></div><button onClick={()=>void removeReport(r.id)} className="rounded-lg border border-[var(--ch-error-text)] px-3 py-2 text-sm font-semibold text-[var(--ch-error-text)]">Delete</button></div>)}</section></main>}
